# Generated by Django 4.0.2 on 2022-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_useripstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images/%Y-%m-%d/'),
        ),
    ]
