# Generated by Django 4.0.2 on 2022-02-28 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_index_together_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsQQQQQQQQQQ', to='shop.category'),
        ),
    ]
